### ISSUE TITLE
How to add collection of placemarks on map?

### ISSUE THREAD

**Issue by ToleubekRauan** [yandex/mapkit-android-demo#10]
I have a list of objects with coordinates, I have to show it on a map, it must be clickable with shown "baloon", thank you.

**Comment by eberkovich** [comment]
You need to use PlacemarkMapObject.
`
ImageProvider resourceBackedImage = ImageProvider.fromResource(this, R.drawable.pushpin);
PlacemarkMapObject placemark = mapObjects.map.getMapObjects().addPlacemark(
      new Point(rowLatitude, columnLongitude), resourceBackedImage);
placemark.addTapListener(customTapListener);
`
Please keep in mind, it is important to reuse ImageProvider if you need to use the same image for several placemarks, otherwise new image will be loaded to memory for each placemark.

**Comment by ToleubekRauan** [comment]
@eberkovich Thank you, friend!
