### ISSUE TITLE
Не переключается текущая локаль карты

### ISSUE THREAD

**Issue by rvgroup** [yandex/mapkit-android-demo#203]
В приложении сделал переключение текущей локали (en - ru).
Весь UI нормально локализуется, а карта не меняется свою локаль.

Пример:

```
        Locale locale = new Locale("ru");
        Locale.setDefault(locale);
```

Как правильно переключать локаль карты?

**Comment by obolsh** [comment]
Локализацию mapkit необходимо указывать в правильном формате: `MapKitFactory.setLocale("ru_RU");` и обязательно прежде чем вызывать инициализацию через `MapKitFactory.initialize("ключи");`

Если формат не правильный, произойдет крах:

`Caused by: java.lang.RuntimeException: Locale parameter is incorrect: divider is missing or not '_'
    Exception stack trace (top 7 entries):
	...
	Java_com_yandex_runtime_i18n_I18nManagerFactory_setLocale__Ljava_lang_String_2
    	...
        at com.yandex.runtime.i18n.I18nManagerFactory.setLocale(Native Method)
        at com.yandex.mapkit.MapKitFactory.initialize(MapKitFactory.java:28)`

Важно! Инициализировать mapkit и указать нужную локализацию можно только 1 раз (первое обращение к mapkit), последующие вызовы соответствующих методов просто игнорируются.
