### ISSUE TITLE
Про размер APK

### ISSUE THREAD

**Issue by DarthMech** [yandex/mapkit-android-demo#204]
Вопрос такой. При сборке проекта с разными minSdkVersion наблюдается разный размер подключаемой библиотеки.
Если в build.gradle указать
```
minSdkVersion 22
targetSdkVersion 29
```
То получаем размер итогового apk 38 mb
![small](https://user-images.githubusercontent.com/11042504/89786998-71ef4300-db25-11ea-8ca0-5532962203e2.png)

Если же в build.gradle указать
```
minSdkVersion 23
targetSdkVersion 29
```
То получаем размер итогового apk 105 mb
![big](https://user-images.githubusercontent.com/11042504/89787012-79aee780-db25-11ea-9b66-7eea6d81d8ff.png)

Можно как-то сократить размер подключаемой либы для minSdkVersion 23?

Эксперимент на пустом проекте. Версия подключаемой библиотеки `implementation 'com.yandex.android:mapkit:3.5.0'.`

**Comment by las1231** [comment]
У меня такая же проблема!!!!!!! Помогите

**Comment by Mikhail57** [comment]
Загружаемый размер не меняется, просто отличается сжатие — для `minSdkVersion` 23+ не сжимаются нативные библиотеки. Инфу по этой особенности можно найти здесь — https://stackoverflow.com/a/63417612

---

APK size for `minSdkVersion` starting from 23 may be different because of changes in the Android API:

> with API 23 the platform can read native libraries without extracting them if they are uncompressed

Yandex.MapKit primarily based on native libraries, so you can face this problem. You can find more info for this question here — https://stackoverflow.com/a/63417612
