### ISSUE TITLE
Не срабатывает SearchManager.SuggestListener

### ISSUE THREAD

**Issue by ivanlp-p** [yandex/mapkit-android-demo#78]
Добрый день! Возникла следующая проблема, не срабатывает SearchManager.SuggestListener. 
Вот код, с помощью которого пытаюсь получить ответ.

`public class MapKit implements SearchManager.SuggestListener {
    private String TAG = "MapKitManager";
    private int RESULT_SIZE = 10;
    private Point CENTER = new Point(55.75, 37.62);
    private double BOX_SIZE = 0.2;
    private final BoundingBox BOUNDING_BOX = new BoundingBox(
            new Point(CENTER.getLatitude() - BOX_SIZE, CENTER.getLongitude() - BOX_SIZE),
            new Point(CENTER.getLatitude() + BOX_SIZE, CENTER.getLongitude() + BOX_SIZE));
    private final SearchOptions SEARCH_OPTIONS = new SearchOptions().setSearchTypes(
            SearchType.GEO.value |
                    SearchType.BIZ.value |
                    SearchType.TRANSIT.value);

    private SearchManager searchManager;
    private List<String> searchResult = new ArrayList<>();
    private KotlinSuggestListener listener;

    @Inject
    public MapKit(Context context) {
        MapKitFactory.setApiKey(ApiKey);
        MapKitFactory.initialize(context);
        SearchFactory.initialize(context);
        searchManager = SearchFactory.getInstance().createSearchManager(SearchManagerType.COMBINED);
    }

    public void start() {
        MapKitFactory.getInstance().onStart();
    }

    public void stop() {
        MapKitFactory.getInstance().onStop();
    }

    public void search(String query, KotlinSuggestListener listener) {
        this.listener = listener;
        searchManager.suggest(query, BOUNDING_BOX, SEARCH_OPTIONS, this);
    }

    @Override
    public void onSuggestResponse(@NonNull List<SuggestItem> list) {
        if (listener != null)
            listener.onSuggest(list);
    }

    @Override
    public void onSuggestError(@NonNull Error error) {
        if (listener != null)
            listener.onError(error);
    }
}`

В логах наблюдаю следующее:
 W/yandex.maps: yandex::maps::runtime::config::internal::ConfigManagerImpl::ConfigManagerImpl: Custom experiments are not allowed
 E/yandex.maps: decltype: Access denied.`

В чем может быть проблема?

**Comment by vbazhenov** [comment]
А примеры из этого репозитория работают с ключом, который используется?

**Comment by ivanlp-p** [comment]
Да, работают. Обнажужилась следующая вещь, ответ приходит когда запрос к api идет из UIThread. Пользуюсь RxJava2, так вот в фоновом потоке ответ не приходит. С чем это может быть связано?

**Comment by vbazhenov** [comment]
Публичные методы мапкита надо вызывать из ui-потока, это явно проверяется при каждом вызове.
Если вызывать их в фоне – будет просто бросаться исключение.

**Comment by azamatdev** [comment]
Why this issue is closed? there is not a right answer to the question! On the net, neither stackoverlow nor other forms have the answers. It would be a lot better if  yandex map team a little bit more supportive and detailed, while explaining something. I still have this error, what would you suggest doing?

`2020-08-04 01:57:31.525 14985-15026/uz.mymax.locationservicecheck W/yandex.maps: yandex::maps::runtime::config::internal::ConfigManagerImpl::ConfigManagerImpl: Custom experiments are not allowed
2020-08-04 01:57:31.525 14985-15025/uz.mymax.locationservicecheck W/yandex.maps: yandex::maps::mapkit::layers::createGroundLayerUpdater: Layer: vskl2, url: https://proxy.mob.maps.yandex.net:443/mapkit2/layers/2.x/vskl2/tiles
2020-08-04 01:57:31.526 14985-15027/uz.mymax.locationservicecheck W/yandex.maps: yandex::maps::mapkit::layers::createGroundLayerUpdater: Layer: vmap2, url: https://proxy.mob.maps.yandex`
